import { Geist, Geist_Mono } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";

import "./style.css";
import "../style/global.scss";
import Header from "@/components/header/header";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import { Provider } from "react-redux";
// import { store } from "@/assets/redux-store/store";

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          <div className="bx-root-app pt-[87px]">{children}</div>
        </Providers>

         {/* <Header />
          <div className="bx-root-app">{children}</div> */}
      </body>
    </html>
    </>
  );
}
