import { Geist, Geist_Mono ,Roboto, Lato} from "next/font/google";
import { ThemeModeScript } from "flowbite-react";

import "swiper/css";
import "./style.css";
import "../style/global.scss";
import Header from "@/components/header/header";
import Providers from "./providers";
import LayoutWrapper from "./layout-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const LatoFornt = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

const  RobotoFornt = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});




export const metadata = {
  title: "Dashboard | Education Web App",
  description: "Generated by Dashboard Web App",
};

// import { Provider } from "react-redux";
// import { store } from "@/assets/redux-store/store";



export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${RobotoFornt.variable} ${LatoFornt.variable} ${geistMono.variable} antialiased bg-[#f7f7f7]`}
      >
        <Providers>
          <LayoutWrapper>
              <div className="bx-root-app ">{children}</div>
          </LayoutWrapper>
        </Providers>

         {/* <Header />
          <div className="bx-root-app">{children}</div> */}
      </body>
    </html>
    </>
  );
}
