"use client";
import React from "react";
import * as FaIcons from "react-icons/fa";
import * as ImIcons from "react-icons/im";
import * as RiIcons from "react-icons/ri";
import * as IoIcons from "react-icons/io5";
import * as MdIcons from "react-icons/md";
import * as TbIcons from "react-icons/tb";
import * as BiIcons from "react-icons/bi";
import * as PiIcons from "react-icons/pi";
import * as GiIcons from "react-icons/gi";
import { IoAnalytics } from "react-icons/io5";
const PageTitleHeading  = (props) => {
  // export const metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };
  const { PathUrl, PageName, ClassBage , IconName} = props;


    // console.log(IconName + "ggg") ;
const cleanIconName = IconName?.trim();

const IconComponent =
  FaIcons[cleanIconName] ||
  ImIcons[cleanIconName] ||
  RiIcons[cleanIconName] ||
  IoIcons[cleanIconName] ||
  MdIcons[cleanIconName] ||
  TbIcons[cleanIconName] ||
  BiIcons[cleanIconName] ||
  PiIcons[cleanIconName] ||
  GiIcons[cleanIconName] ||
  null;

const FinalIcon = IconComponent || IoAnalytics;

  return (
    <>
      <section className={`bx-page-heading-section`}>
        <div className="container-full w-full mx-auto ">
          <div className={`bx-page-overlay`}>
            <div className={`grid grid-cols-12 `}>
              <div className={`col-span-12 `}>
                
                <h2
                  className={`animate__animated animate__fadeInLeft text-[25px] flex items-center`}
                  style={{ animationDelay: "0.1s", animationDuration: "1s" }}
                >
                  <span className={`pr-[9px]`}> <FinalIcon size={20} /></span>
                  {PageName}
                </h2>

                {/* <Breadcrumbs BreadcrumbsTitles={PageName} /> */}
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default PageTitleHeading ;
