import React from "react";

const PageTitleHeading  = (props) => {
  // export const metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };

  const { PathUrl, PageName, ClassBage } = props;
  return (
    <>
      <section>
        <div className="container-full w-full mx-auto">
          <div className="bx-page-overlay">
            <div className={`grid grid-cols-12 `}>
              <div className={`col-span-12 `}>
                <h2
                  className={`animate__animated animate__fadeInLeft`}
                  style={{ animationDelay: "0.1s", animationDuration: "1s" }}
                >
                  {PageName}
                </h2>

                {/* <Breadcrumbs BreadcrumbsTitles={PageName} /> */}
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default PageTitleHeading ;
